version: 2
jobs:
  build-linux-nix:
    docker:
      - image: nixos/nix
    working_directory: ~/inline-java
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash
            nix-env -f nixpkgs.nix -iA stack
      - run:
          name: Compute cache key
          command: |
              (echo shell.nix; echo nixpkgs.nix; find . -name "*.cabal" -o -name "stack.yaml" -type f) | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
      - run:
          name: Build dependencies
          command: |
            stack --no-terminal --nix build --only-snapshot --prefetch --test --bench -j2
      - save_cache:
          key: inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build project
          command: stack --nix --no-terminal build -j2 --pedantic --test --bench --no-run-tests --no-run-benchmarks
      - run:
          name: Test
          command: stack --nix --no-terminal test

  build-bazel:
    docker:
      - image: nixos/nix
    working_directory: ~/sparkle
    environment:
      - NIXRUN: nix-shell -I nixpkgs=./nixpkgs.nix -p gcc bazel --run
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash binutils zip
            $NIXRUN "echo nix dependencies installed"
      - run:
          name: Build project
          command: $NIXRUN "bazel build --jobs 2 //..."

  build-darwin-brew:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Prepare system
          command: |
            mkdir -p ~/.local/bin
            curl -Lk https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin
      - run:
          name: Install software
          command: |
            brew update
            brew install gradle
      - run:
          name: Compute cache key
          command: |
            find . -name "*.cabal" -o -name "stack.yaml" -type f | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
      - run:
          name: Build dependencies
          command: |
            ~/.local/bin/stack --no-terminal build -j2 --only-snapshot --prefetch --test --bench
      - save_cache:
          key: inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build and test
          command: |
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
            ~/.local/bin/stack --no-terminal build -j2 \
                --test \
                --extra-lib-dirs=$JAVA_HOME/jre/lib/server/ \
                --extra-include-dirs=$JAVA_HOME/include/ \
                --extra-include-dirs=$JAVA_HOME/include/darwin/

workflows:
  version: 2
  build:
    jobs:
      - build-linux-nix
      - build-bazel
      - build-darwin-brew
